version: "2"
services:
  app:
    container_name: flask_webapp
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"

    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  
  web:
    image: nginx:latest
    volumes:
            - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 80:80


